### ISSUE TITLE
Creating the environment for adding end-to-end tests for SDX

### ISSUE THREAD

**Issue by italovalcy** [atlanticwave-sdx/sdx-end-to-end-tests#1]
We should create an environment for daily running end-to-end tests on the SDX controller (whole environment) as we have for Kytos: https://github.com/kytos-ng/kytos-end-to-end-tests/

We should leverage GitHub actions for that.

**Comment by italovalcy** [comment]
We should evaluate if it is valid to pay for using a paid version of GitHub actions or do something on-premises.

**Comment by sajith** [comment]
Our GitHub Actions usage has been [pretty minimal](https://github.com/organizations/atlanticwave-sdx/settings/billing/summary), especially in the quieter times.

![image](https://github.com/atlanticwave-sdx/sdx-end-to-end-tests/assets/23618/12a625ff-2f18-4d74-a490-4b1eb2597637)

I suppose we can try GitHub first, and then on-prem if we hit the 3000 minutes limit.

**Comment by italovalcy** [comment]
Basic tests were added to an internal gitlab environment, and they will be migrated to GitHub soon.
